import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppStoreProvider from "../redux/services/provider";
import NavBar from "@/components/Navbar";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "rendercon talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppStoreProvider>
        <ToastContainer/>
          <NavBar/>
          <div className="mx-auto mx-w-screen-2xl px-8 md:px-12">
            {children}
          </div>
         
        </AppStoreProvider>
      </body>
    </html>
  );
}
